import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from "react-router-dom";
const HeroSection = () => {
    const navigate = useNavigate();
    // tones shared by band/plate/curve (prevents seams)
    const BEIGE = "#dcc7af";
    const PLATE = "#e8dccb";
    return (_jsx("section", { className: "relative w-full overflow-visible", children: _jsxs("div", { className: "relative w-full", style: { background: BEIGE }, children: [_jsx("div", { className: "absolute right-6 top-6 flex flex-col items-end gap-3 z-10", children: _jsx("button", { onClick: () => navigate("/auth"), className: "px-5 py-2.5 text-sm sm:text-base font-medium bg-[#F44E1A] border border-black hover:brightness-110 active:translate-y-px transition", children: "Log in" }) }), _jsxs("div", { className: "flex flex-col items-center justify-center text-center px-6 sm:px-8 pt-10 sm:pt-12 pb-16", children: [_jsx("img", { src: "/MIDIMIJAI-LOGO.png", alt: "MIDIMIJAI", className: "h-[260px] sm:h-[320px] lg:h-[360px] select-none mb-6 mx-auto", draggable: false }), _jsx("div", { className: "rounded-xl px-10 sm:px-12 py-4 mx-auto plate-glow", style: { background: PLATE }, children: _jsxs("p", { className: "text-[18px] sm:text-[20px] leading-relaxed text-[#3a2a20] font-medium text-glow-white", children: ["Create, edit, and transform MIDI like never before with AI. Deeply customizable", _jsx("br", {}), "and easy to use for producers, musicians, and beginners."] }) }), _jsx("button", { onClick: () => navigate("/auth"), className: "\r\n              mt-8\r\n              inline-flex items-center justify-center\r\n              h-14 px-14\r\n              bg-[#F44E1A] text-black text-[20px]\r\n              hover:brightness-110 active:translate-y-px transition\r\n            ", children: "Start now" })] }), _jsx("div", { className: "relative w-full h-[110px]", style: { background: BEIGE }, children: _jsxs("svg", { viewBox: "0 0 100 20", preserveAspectRatio: "none", className: "absolute inset-0 w-full h-full pointer-events-none", children: [_jsx("rect", { x: "0", y: "0", width: "100", height: "20", fill: BEIGE }), _jsx("path", { d: "M0,0 C25,28 75,28 100,0 L100,20 L0,20 Z", fill: BEIGE })] }) })] }) }));
};
export default HeroSection;
